version: 1
disable_existing_loggers: false
objects:
  queue:
    class: queue.Queue
    maxsize: 1000
formatters:
  simple:
    format: '[%(levelname)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'
  json:
    (): logger.logger.MyJSONFormatter
    fmt_keys:
      level: levelname
      message: message
      timestamp: timestamp
      logger: name
      module: module
      function: funcName
      line: lineno
      thread_name: threadName
handlers:
  stderr:
    class: logging.StreamHandler
    level: WARNING
    formatter: simple
    stream: ext://sys.stderr
  file_json:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    maxBytes: 10000
    backupCount: 3
  z_queue_listener:
    class: logger.logger.QueueListenerHandler
    handlers:
      - cfg://handlers.stderr
      - cfg://handlers.file_json
    queue: cfg://objects.queue
    respect_handler_level: true

loggers:
  root:
    level: DEBUG
    handlers:
    - z_queue_listener